Repository LLNL/blt, pull requests merged in 2020-04, with the labels that each got.

#354 Feature/white238/azureclean
  .travis.yml
  README.md
  appveyor.yml
  azure-pipelines.yml
  docs/api/target.rst
  tests/internal/CMakeLists.txt
Labels: CI

#356 Fix duplicate MPI link flag
  RELEASE-NOTES.md
  cmake/thirdparty/SetupMPI.cmake
Labels: flags

#357 Very selectively remove possible spaces in link flags
  cmake/thirdparty/SetupMPI.cmake
Labels: bug, flags

#359 Add NVIDIA SDK path to the CUDA link flags
  RELEASE-NOTES.md
  azure-pipelines.yml
  cmake/thirdparty/SetupCUDA.cmake
Labels: cuda, feature, flags

#361 Two small fixes...
  cmake/BLTPrivateMacros.cmake
  cmake/thirdparty/SetupMPI.cmake
Labels: flags
