Repository LLNL/blt, pull requests merged in 2020-03, with the labels that each got.

#345 Fix heading in blt_assert_exists() sphinx documentation
  docs/api/utility.rst
Labels: documentation

#347 Remove googletest adding -Werror
  thirdparty_builtin/benchmark-1.5.0/CMakeLists.txt
  thirdparty_builtin/googletest-master-2020-01-07/googletest/cmake/internal_utils.cmake
  thirdparty_builtin/patches/gbenchmark-2020-03-11-remove-werror.patch
  thirdparty_builtin/patches/gtest-2020-03-11-remove-werror.patch
Labels: TPL, flags

#350 Feature/white238/clangformat
  CONTRIBUTING.md
  README.md
  RELEASE-NOTES.md
  cmake/BLTOptions.cmake
  cmake/SetupCodeChecks.cmake
  cmake/run-clang-format.py
  cmake/thirdparty/SetupThirdParty.cmake
  docs/api/code_check.rst
  tests/internal/CMakeLists.txt
Labels: TPL, code checks

#351 Fix docs slightly
  docs/api/code_check.rst
Labels: documentation
