Repository LLNL/blt, pull requests merged in 2021-04, with the labels that each got.

#472 Only set INTERFACE scope on INTERFACE targets
  cmake/BLTPrivateMacros.cmake
Labels: bug

#473 Changes required for ROCm 4
  cmake/thirdparty/SetupHIP.cmake
Labels: hip

#474 Restructure tutorial
  docs/api/target_properties.rst
  docs/index.rst
  docs/tutorial/adding_tests.rst
  docs/tutorial/advanced_topics.rst
  docs/tutorial/bare_bones/CMakeLists.txt
  docs/tutorial/common_hpc_dependencies.rst
  docs/tutorial/creating_documentation.rst
  docs/tutorial/creating_execs_and_libs.rst
  docs/tutorial/creating_targets.rst
  docs/tutorial/exporting_targets.rst
  docs/tutorial/external_dependencies.rst
  docs/tutorial/getting_started.rst
  docs/tutorial/host_configs.rst
  docs/tutorial/importing_targets.rst
  docs/tutorial/index.rst
  docs/tutorial/object_libraries.rst
  docs/tutorial/portable_compiler_flags.rst
  docs/tutorial/third_party_libraries.rst
Labels: documentation

#477 Document release process
  docs/developer/index.rst
  docs/developer/release_process.rst
  docs/index.rst
Labels: documentation

#479 0.4.0 mergeback
  RELEASE-NOTES.md
  SetupBLT.cmake
Labels: release

#480 fix import TPL example
  docs/tutorial/third_party_libraries.rst
Labels: bug, documentation

#487 Fix scaling of logo on RTD
  docs/_static/style.css
Labels: bug, documentation
