Repository LLNL/blt, pull requests merged in 2021-02, with the labels that each got.

#454 CTest to JUnit conversion
  docs/tutorial/unit_testing.rst
  tests/ctest-to-junit.xsl
Labels: CI, testing

#456 Clarified comment in RELEASE-NOTES
  RELEASE-NOTES.md
Labels: documentation

#457 Feature/gitlabci
  .gitlab-ci.yml
  .gitlab/build_and_test.sh
  .gitlab/build_lassen.yml
  .gitlab/build_quartz.yml
  .mailmap
  host-configs/llnl/toss_3_x86_64_ib/gcc@8.3.1.cmake
  host-configs/llnl/toss_3_x86_64_ib/pgi@20.1.cmake
Labels: CI, testing

#459 Re-add previous iteration of openMP patching logic
  RELEASE-NOTES.md
  cmake/BLTPrivateMacros.cmake
Labels: bug, fortran, openmp
